<a href="https://colab.research.google.com/github/ncerutti/DE-zoomcamp/blob/main/Homework_data_talks_club_data_extraction_and_ingestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [10]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

values = []

for sqrt_value in generator:
    print(sqrt_value)
    values.append(sqrt_value)

print(sum(values))

# ANSWER 1: 8.382332347441762

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
8.382332347441762

In [11]:
# Example usage:
limit = 13
generator = square_root_generator(limit)

values = []

for sqrt_value in generator:
    print(sqrt_value)
    values.append(sqrt_value)

# ANSWER 2: 3.605551275463989

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
3.1622776601683795
3.3166247903554
3.4641016151377544
3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [12]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

ages = []

for person in people_1():
    print(person)
    ages.append(person["Age"])

print(sum(ages))

def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)
    ages.append(person["Age"])

print(sum(ages))

# ANSWER 3: 353

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
140
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}
353

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

In [4]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [5]:
import dlt

people_pipeline = dlt.pipeline(
  destination="duckdb",
  dataset_name="people_total",
)

run_info = people_pipeline.run(people_1,
                              table_name="people",
                              primary_key="id",
                              write_disposition="merge")

print(run_info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.55 seconds
1 load package(s) were loaded to destination duckdb and into dataset people_total
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707177550.027349 is LOADED and contains no failed jobs

In [6]:
import duckdb

conn = duckdb.connect(f"{people_pipeline.pipeline_name}.duckdb")

# Check people_1
conn.sql(f"SET search_path = '{people_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))
people = conn.sql("SELECT * FROM people").df()
display(people)

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ people              │
└─────────────────────┘

   id      name  age    city       _dlt_load_id         _dlt_id
0   5  Person_5   30  City_A  1707177550.027349  coc39tBCeHUpTQ
1   2  Person_2   27  City_A  1707177550.027349  jsCUN095gsJfWQ
2   1  Person_1   26  City_A  1707177550.027349  2OCkezh3nECi5A
3   4  Person_4   29  City_A  1707177550.027349  lMKldi6pmBEyGA
4   3  Person_3   28  City_A  1707177550.027349  bTv5FS3k7jMycA

In [7]:
# Add people_2

run_info = people_pipeline.run(people_2,
                              table_name="people",
                              primary_key="id",
                              write_disposition="merge")

print(run_info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.40 seconds
1 load package(s) were loaded to destination duckdb and into dataset people_total
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1707177561.3080575 is LOADED and contains no failed jobs

In [8]:
people = conn.sql("SELECT * FROM people").df()
display(people)

   id      name  age    city        _dlt_load_id         _dlt_id occupation
0   2  Person_2   27  City_A   1707177550.027349  jsCUN095gsJfWQ       None
1   1  Person_1   26  City_A   1707177550.027349  2OCkezh3nECi5A       None
2   5  Person_5   35  City_B  1707177561.3080575  dNdqoXl1H/Ugkw      Job_5
3   8  Person_8   38  City_B  1707177561.3080575  rWahAYnLr0IjrQ      Job_8
4   7  Person_7   37  City_B  1707177561.3080575  Mn1JLrLjaS0+Kw      Job_7
5   4  Person_4   34  City_B  1707177561.3080575  nNjL1kkwOaZRwA      Job_4
6   3  Person_3   33  City_B  1707177561.3080575  AxmFJwl8X9iI9A      Job_3
7   6  Person_6   36  City_B  1707177561.3080575  A+ou7F1EM2JGFA      Job_6

In [9]:
total_ages = conn.sql("SELECT sum(Age) FROM people").df()
print(total_ages)

# ANSWER 4: 266???

   sum(Age)
0     266.0

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX